config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  resources :team_seasons


  get 'other/index'
  get 'other/' => 'other#index'
  get 'other/bar'
  get 'other/line'
  get 'other/scatter'
  get 'other/arc'
  get 'other/tree'
  get 'other/cluster'
  get 'other/pack'
  get 'other/bubble'
  get 'other/histogram'
  get 'other/treemap'
  get 'other/map'
  get 'other/barchart' => 'other#barchart'
  get 'other/barchartcsv' => 'other#barchartcsv'

  
  get 'bar' => 'bar#index'
  get 'bar/json' => 'bar#json'

  get 'line' => 'line#index'

  get 'scatter' => 'scatter#index'
  get '/scatterchart' => 'scatter#scatterchart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team_season.rb
class TeamSeason < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bar_controller.rb
class BarController < ApplicationController
  
  require 'csv'
  
  def index
    @team_seasons = TeamSeason.all
  end


	def json
	    @csv = CSV.open(Rails.root.join('lib', 'data', '2016-17.csv'),"r").to_a.sort_by{|arr| arr[5].to_i}
	    @json = []

	    @csv.each_with_index{|row,i|
	      next if i == 0
	      next if row[2] == "team_name"
	      @hsh = {}
	      @hsh["team_name"] = row[2]
	      @hsh["team_color"] = row[3]
	      @hsh["salary"] = row[4]
	      @hsh["wins"] = row[5]
	      @json << @hsh
	    }

	    render json: @json
	end

#	def csv
#	    @csv = CSV.open(Rails.root.join('lib', 'data', '2016-17.csv'),"r").to_a.sort_by{|arr| arr[5].to_i}
#	    render csv: @csv
#	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/line_controller.rb
class LineController < ApplicationController
  def index
  end
end

app/controllers/other_controller.rb
class OtherController < ApplicationController
  def index
  end

  def bar
  end


  def line
  end

  def scatter
  end

  def arc
  end

  def tree
  end

  def cluster
  end

  def pack
  end

  def bubble
  end

  def histogram
  end

  def treemap
  end

  def map
  end
end

app/controllers/scatter_controller.rb
class ScatterController < ApplicationController
	
	require 'csv'
	def index
	@team_seasons = TeamSeason.all
	end


	def graph
	    @csv = CSV.open(Rails.root.join('app', 'views', 'team_seasons', '2016-17.csv'),"r").to_a
	    @json = {"chartType": "Scatterplot", "attribute1" => "x", "attribute2" => "y", "data" => []}

	    @csv.each_with_index{|row,i|
	      next if i == 0
	      @hsh = {}
	      @hsh["x"] = row[6]
	      @hsh["y"] = row[3]
	      @json["data"] << @hsh
	    }

	    render json: @json
	end

	def scatterchart
		@csv = CSV.open(Rails.root.join('lib', 'data', '2016-17.csv'),"r").to_a
		@json = []

		@csv.sort_by{|row| row[5] }.each_with_index{|row,i|
		  next if i == 0
		  @hsh = {}
		  @hsh["team_name"] = row[2]
		  @hsh["team_color"] = row[3]
		  @hsh["salary"] = row[4]
		  @hsh["wins"] = row[5]
		  @json << @hsh
		}

		render json: @json
	end

end

app/controllers/team_seasons_controller.rb
class TeamSeasonsController < ApplicationController
  before_action :set_team_season, only: [:show, :edit, :update, :destroy]

  # GET /team_seasons
  # GET /team_seasons.json
  require 'csv'
  def index
    @team_seasons = TeamSeason.all
  end


  def graph
    @csv = CSV.open(Rails.root.join('app', 'views', 'team_seasons', '2016-17.csv'),"r").to_a
    @json = {"chartType": "Scatterplot", "attribute1" => "x", "attribute2" => "y", "data" => []}

    @csv.each_with_index{|row,i|
      next if i == 0
      @hsh = {}
      @hsh["x"] = row[6]
      @hsh["y"] = row[3]
      @json["data"] << @hsh
    }

    render json: @json
  end

  # GET /team_seasons/1
  # GET /team_seasons/1.json
  def show
  end

  # GET /team_seasons/new
  def new
    @team_season = TeamSeason.new
  end

  # GET /team_seasons/1/edit
  def edit
  end

  # POST /team_seasons
  # POST /team_seasons.json
  def create
    @team_season = TeamSeason.new(team_season_params)

    respond_to do |format|
      if @team_season.save
        format.html { redirect_to @team_season, notice: 'Team season was successfully created.' }
        format.json { render :show, status: :created, location: @team_season }
      else
        format.html { render :new }
        format.json { render json: @team_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_seasons/1
  # PATCH/PUT /team_seasons/1.json
  def update
    respond_to do |format|
      if @team_season.update(team_season_params)
        format.html { redirect_to @team_season, notice: 'Team season was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_season }
      else
        format.html { render :edit }
        format.json { render json: @team_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_seasons/1
  # DELETE /team_seasons/1.json
  def destroy
    @team_season.destroy
    respond_to do |format|
      format.html { redirect_to team_seasons_url, notice: 'Team season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_season
      @team_season = TeamSeason.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_season_params
      params.require(:team_season).permit(:index)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bar_helper.rb
module BarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_helper.rb
module LineHelper
end

app/helpers/other_helper.rb
module OtherHelper
end

app/helpers/scatter_helper.rb
module ScatterHelper
end

app/helpers/team_seasons_helper.rb
module TeamSeasonsHelper
end

app/views/bar/index.html.erb
<outer>
  <h1 align="center" class="svg_txt_1">Bar Chart</h1>
  <h4 align="center">from js array (hand coded)</h4>
  
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
    var data = [50,100,150,175,200,225,275,300]

    var width = "100%"
    var height = "360"

      var canvas = d3.select("outer").append("svg")
        .attr("height",height)
        .attr("width",width)
        .append("g")
          .attr("transform","translate(700,50)");

      canvas.selectAll("rect")
        .data(data)
        .enter()
          .append("rect")
          .attr("width",20)
          .attr("height",function(data){ return data })
          .attr("x",function(data,i){ return i*30 })
          .attr("fill","#005083");
  </script>
</outer>

<br><br><hr><br><br>

<outer1>
  <h1 align="center" class="svg_txt_1">Bar Chart</h1>
  <h4 align="center">from json, colors from data</h4>
  
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
    var jsonData = d3.json('/bar/json.json', function(jsonData){

      var canvas = d3.select("outer1").append("svg")
        .attr("height","500")
        .attr("width","100%")
        .append("g")
          .attr("transform","translate(300,60)");

      canvas.selectAll("rect")
        .data(jsonData)
        .enter()
          .append("rect")
          .attr("width",30)
          .attr("height",function(d){ return d.wins * 10 })
          .attr("x",function(data,i){ return i*40 })
          .attr("fill",function(d){ return d.team_color });

      });

  </script>
</outer1>

<br><br><hr><br><br>

<outer2>
  <h1 align="center" class="svg_txt_1">Bar Chart</h1>
  <h4 align="center">from csv in app/public</h4>
  
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
    var data = d3.csv('/2016-17_public.csv', function(data){

      var canvas = d3.select("outer2").append("svg")
        .attr("height","500")
        .attr("width","100%")
        .append("g")
          .attr("transform","translate(300,60)");

      canvas.selectAll("rect")
        .data(data)
        .enter()
          .append("rect")
          .attr("width",30)
          .attr("height",function(d){ return d.wins * 10 })
          .attr("x",function(data,i){ return i*40 })
          .attr("fill",function(d){ return d.team_color });

      });

  </script>
</outer2>

<br><br><hr><br><br>

<outer3>
  <h1 align="center" class="svg_txt_1">Bar Chart</h1>
    <h4 align="center">from json y-scaled</h4>
  
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
    var data = d3.json('bar/json.json', function(data){

      var width = "100%";
      var height = 500;
      
      var yScale = d3.scale.linear()
        .domain([0,81])
        .range([0,height-5]);

      var canvas = d3.select("outer3").append("svg")
        .attr("height",height)
        .attr("width",width)
        .append("g")
        .attr("transform","translate(150,60)");

      canvas.selectAll("rect")
        .data(data)
        .enter()
          .append("rect")
          .attr("width",30)
          .attr("height",function(d){ return yScale(d.wins) })
          .attr("x",function(data,i){ return i * 34 })
          .attr("fill",function(d){ return d.team_color });
    });

  </script>

  </script>
</outer3>

<br><br>
<hr>
<br><br>


<outer4>
  <h1 align="center" class="svg_txt_1">Bar Chart</h1>
    <h4 align="center">from json, inverted </h4>
  
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
    var data = d3.json('bar/json.json', function(data){

      var width = "100%";
      var height = 500;
      
      var yScale = d3.scale.linear()
        .domain([0,60])
        .range([height-5,5]);

      var canvas = d3.select("outer4").append("svg")
        .attr("height",height)
        .attr("width",width)
        .append("g")
        .attr("transform","translate(150,60)");

      canvas.selectAll("rect")
        .data(data)
        .enter()
          .append("rect")
          .attr("width",30)
          .attr("x",function(d,i){ return i * 34 })
          .attr("y",function(d){ return yScale(d.wins) })
          .attr("height",function(d){ return yScale(d.wins) })
          .attr("fill",function(d){ return d.team_color });
    });

  </script>

  </script>
</outer4>



<br><br>
<hr>
<br><br>



<outer5>
  <h1 align="center" class="svg_txt_1">Bar Chart</h1>
    <h4 align="center">from json, with labels, clumsily x- and y-scaled </h4>
  
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
    var data = d3.json('bar/json.json', function(data){

      var width = 900;
      var height = 500;
      
      var xScale = d3.scale.linear()
        .domain([1,30])
        .range([5,495]);
      
      var yScale = d3.scale.linear()
        .domain([0,60])
        .range([height-20,20]);

      var canvas = d3.select("outer5").append("svg")
        .attr("height",height)
        .attr("width",width)
        .append("g")
        .attr("transform","translate(150,60)");

      canvas.selectAll("rect")
        .data(data)
        .enter()
          .append("rect")
          .attr("width",15)
          .attr("x",function(d,i){ return xScale(i) })
          .attr("y",function(d){ return yScale(d.wins) })
          .attr("height",function(d){ return yScale(d.wins) })
          .attr("fill",function(d){ return d.team_color });

      canvas.selectAll("text")
        .data(data)
        .enter()
          .append("text")

            .text(function(d){ return d.team_name })
            .style("text-anchor","end")
            .attr("dx", function(d,i){ return xScale(i) + 10 })
            .attr("dy", function(d){ return yScale(d.wins) - 15 })
            .attr("fill",function(d){ return d.team_color }); 
    });

  </script>
</outer5>



<br><br>
<hr>
<br><br>


<outer6>
  <h1 align="center" class="svg_txt_1">Bar Chart</h1>
    <h4 align="center">from csv, with labels, no scales </h4>
  
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
    var data = d3.csv('/2016-17_public.csv', function(data){

      var canvas = d3.select("outer6").append("svg")
        .attr("height","500")
        .attr("width","100%")
        .append("g")
          .attr("transform","translate(200,60)");

      canvas.selectAll("rect")
        .data(data)
        .enter()
          .append("rect")
          .attr("width",30)
          .attr("height",function(d){ return d.wins * 10 })
          .attr("x",function(data,i){ return i*40 })
          .attr("fill",function(d){ return d.team_color });

      canvas.selectAll("text")
        .data(data)
        .enter()
          .append("text")
          .text(function(d){ return d.team_name })
          .attr("y",-22)
          .attr("x",function(d,i){ return i*40 })
          .attr("fill",function(d){ return d.team_color });
      });

  </script>
</outer6>


<br><br>
<hr>
<br><br>


<chart>
    <h1 align="center" class="svg_txt_1">Just The Scales!</h1>
    <h4 align="center">no data </h4>
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>
var width = 1500;
var height = 600;
var padding = {top: 20, right: 40, bottom: 20, left: 40};
var canvas = d3.select("chart")
              .append("svg")
              .attr("width",width)
              .attr("height",height);

var group = canvas.append("g")
            .attr("transform", "translate(" + padding.left + "," + padding.top + ")");

var x = d3.scaleLinear()
    .domain([0,82])
    .range([padding.left, width-padding.right*2]);
    //.padding(1);

var y = d3.scaleLinear()
    .domain([50000000,170000000])
    .range([height-padding.bottom*3,padding.top]);

group.append("g")
  .attr("transform", "translate(" + padding.left + ",0)")
  .attr("class", "axis")
  .call(d3.axisLeft(y)
      .ticks(10));

group.append("g")
  .attr("transform", "translate(0,550)")
  .attr("class", "axis")
  .call(d3.axisBottom(x)
      .ticks(5));

</script>
</chart>

<br><br>
<hr>
<br><br>


<chart1>
    <h1 align="center" class="svg_txt_1">Scales with scaled Data</h1>
    <h4 align="center"> data </h4>
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>

  var data = d3.csv('/2016-17_public.csv', function(data){

    var width = 1500;
    var height = 600;
    var padding = {top: 20, right: 40, bottom: 20, left: 40};
    
    var canvas = d3.select("chart1")
                  .append("svg")
                  .attr("width",width)
                  .attr("height",height);

    var x = d3.scaleLinear()
        .domain([0,30])
        .range([padding.left, 1400]);

    var y = d3.scaleLinear()
            .domain([0,82])
            .range([height,0]);

    var axisGroup = canvas.append("g")
                .attr("transform", "translate(" + padding.left + "," + padding.top + ")");
// Draw Axes
    axisGroup.append("g")
      .attr("transform", "translate(" + padding.left + ",0)")
      .attr("class", "axis")
      .call(d3.axisLeft(y)
          .ticks(10));

    axisGroup.append("g")
      .attr("transform", "translate(1400,0)")
      .attr("class", "axis")
      .call(d3.axisRight(y)
          .ticks(10));

    axisGroup.append("g")
      .attr("transform", "translate(0,550)")
      .attr("class", "axis")
      .call(d3.axisBottom(x)
        .ticks(30)); 


// Draw Bars
    var barsGroup = canvas.append("g")
                .attr("transform", "translate(" + padding.left*2 + "," + padding.top + ")");

    barsGroup.selectAll("rect")
      .data(data)
      .enter()
        //.attr("transform", "translate(" + padding.left + ",0)")
        .append("rect")
        //.attr("width",(width-((padding.right*2)+(padding.left*2)))/50)
        //var barWidth = 30
        .attr("x", function(d,i){ return x(i)-33 })  
        .attr("width", width/50 )
        //.attr("y", function(d,i){ return x(i)-33 })  
        .attr("y", 0)  
        .attr("height", function(d){ return y(d.wins) })
        .attr("fill", function(d){ return d.team_color });


  });
</script>
</chart1>

<br><br>
<hr>
<br><br>

<div class="chart-container">
<chart2>
    <h1 align="center" class="svg_txt_1">Scaled data adjusted</h1>
    <h4 align="center"> unlike the above, this is an accurate representation of the data </h4>
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>

  var data = d3.csv('/2016-17_public.csv', function(data){

    var width = 1500;
    var height = 500;
    var padding = { top: 20, right: 40, bottom: 20, left:40 }
    
    var canvas = d3.select("chart2")
                  .append("svg")
                  .attr("width",width)
                  .attr("height",height);

    var x = d3.scaleLinear()
        .domain([0,30])
        .range([padding.left,width-padding.right]);
        //.range([0,width]);

    var y = d3.scaleLinear()
            .domain([0,82])
            .range([height-padding.bottom,padding.top]);
            //.range([height,0]);

    var axisGroup = canvas.append("g")
            //.attr("transform", "translate(" + padding.left + "," + padding.top + ")");

    axisGroup.append("g")
          .attr("transform", "translate(" + padding.left + "," + (padding.bottom - 5) + ")")
          .attr("class", "axis")
          .call(d3.axisLeft(y)
              .ticks(10));

      axisGroup.append("g")
        .attr("transform", "translate(" + (width - padding.right + 3) + "," + (padding.bottom - 5) + ")")
        .attr("class", "axis")
        .call(d3.axisRight(y)
            .ticks(10));

//      axisGroup.append("g")
//        .attr("transform", "translate(40,500)")
//        .attr("class", "axis")
//        .call(d3.axisBottom(x)
//          .ticks(0));


    var barsGroup = canvas.append("g")
                .attr("transform", "translate(3," + ( padding.bottom - 5 ) + ")");

// Draw Bars
    barsGroup.selectAll("rect")
      .data(data)
      .enter()
        //.attr("transform", "translate(0," + padding.bottom + ")")
        .append("rect")
        .attr("x", function(d,i){ return x(i) })  
        .attr("width", width/33 )
        .attr("y", function(d){ return y(d.wins) })  
        .attr("height", function(d){ return y(d.wins) })
        .attr("fill", function(d){ return d.team_color });

  });
</script>
</chart2>
</div>

<br><br>
<hr>
<br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hi David</title>
    <%= csrf_meta_tags %>

    <link rel="shortcut icon" href="/old_tablet.jpg"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/header_nav' %>
    <%= yield %>
  </body>
</html>

app/views/line/index.html.erb
<lineone>

	<script src="https://d3js.org/d3.v4.min.js"></script>
	<script>
		var width = 2300;
		var height = 900;
		var padding = 100

		var canvas = d3.select("lineone")
			.append("svg")
			.attr("width",width)
			.attr("height",height);

		canvas.append("g")
			.append("rect")
				.attr("width",width)
				.attr("height",3)
				.attr("fill","black")
				.attr("x",padding)
				.attr("y",height-10);

		canvas.append("g")
			.append("rect")
				.attr("width",3)
				.attr("height",height)
				.attr("fill","black")
				.attr("x",padding)
				.attr("y",10);				
	</script>

</linetwo>

app/views/other/arc.html.erb
<h1>Other#arc</h1>
<p>Find me in app/views/other/arc.html.erb</p>

app/views/other/bubble.html.erb
<h1>Other#bubble</h1>
<p>Find me in app/views/other/bubble.html.erb</p>

app/views/other/cluster.html.erb
<h1>Other#cluster</h1>
<p>Find me in app/views/other/cluster.html.erb</p>

app/views/other/histogram.html.erb
<h1>Other#histogram</h1>
<p>Find me in app/views/other/histogram.html.erb</p>

app/views/other/index.html.erb
<h2> this is the index for other </h2>

<p>Check out: 
	<br><a href="/other/bar">Bar</a>
	<br><a href="/other/line">Line</a>
	<br><a href="/other/scatter">Scatter</a>
	<br><a href="/other/arc">Arc</a>
	<br><a href="/other/tree">Tree</a>
	<br><a href="/other/cluster">Cluster</a>
	<br><a href="/other/pack">Pack</a>
	<br><a href="/other/tree">Bubble</a>
	<br><a href="/other/treemap">treemap</a>
	<br><a href="/other/map">map</a>
</p>

app/views/other/line.html.erb
<h1>Other#line</h1>
<p>Find me in app/views/other/line.html.erb</p>

app/views/other/map.html.erb
<h1>Other#map</h1>
<p>Find me in app/views/other/map.html.erb</p>

app/views/other/pack.html.erb
<h1>Other#pack</h1>
<p>Find me in app/views/other/pack.html.erb</p>

app/views/other/scatter.html.erb
<h1>Other#scatter</h1>
<p>Find me in app/views/other/scatter.html.erb</p>

app/views/other/tree.html.erb
<h1>Other#tree</h1>
<p>Find me in app/views/other/tree.html.erb</p>


<script>
	
	var canvas = d3.select("body").append("svg")
		.attr("width",500)
		.attr("height",500)
		.append("g")
			.attr("transform","translate(50,50)");

	var tree = d3.layout.tree()
				.size([400,400]);

	d2.csv('2016-17.csv', function(data){
		var nodes = tree.nodes(data);
		var links = tree.links(nodes);

	});

</script>

app/views/other/treemap.html.erb
<h1>Other#treemap</h1>
<p>Find me in app/views/other/treemap.html.erb</p>

app/views/shared/_header_nav.html.erb
<nav class="header-cont" role="navigation">
  <div class="header">
      <a class="navbar-link" href="/home">Home</a> | &nbsp; <a class="navbar-link" href="/team_seasons">Data</a> | &nbsp; <a class="navbar-link" href="/bar">Bar</a> &nbsp; | &nbsp; <a class="navbar-link" href="/scatter">Scatter</a> | &nbsp; <a class="navbar-link" href="/line">Line</a> | &nbsp; <a class="navbar-link" href="/other">Other</a> 
    </div>
  </div>
</nav>
<p><br/><br/></p>
<p><br/><br/></p>

app/views/team_seasons/_form.html.erb
<%= form_for(team_season) do |f| %>
  <% if team_season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_season.errors.count, "error") %> prohibited this team_season from being saved:</h2>

      <ul>
      <% team_season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %>
    <%= f.text_field :index %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_seasons/edit.html.erb
<h1>Editing Team Season</h1>

<%= render 'form', team_season: @team_season %>

<%= link_to 'Show', @team_season %> |
<%= link_to 'Back', team_seasons_path %>

app/views/team_seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Seasons</h1>

<table>
  <thead>
    <tr>
      <th>season</th>
      <th>city</th>
      <th>team</th>
      <th>color</th>
      <th>salary</th>
      <th>wins</th>
      <th>losses</th>
      <th>win %</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_seasons.each do |team_season| %>
      <tr>
        <td><%= team_season.season %></td>
        <td><%= team_season.team_city %></td>
        <td><%= team_season.team_name %></td>
        <td><%= team_season.team_color %></td>
        <td><%= team_season.salary %></td>
        <td><%= team_season.wins %></td>
        <td><%= team_season.losses %></td>
        <td><%= team_season.win_percentage.to_s[1..-1] %></td>
        <td><%= link_to 'Show', team_season %></td>
        <td><%= link_to 'Edit', edit_team_season_path(team_season) %></td>
        <td><%= link_to 'Destroy', team_season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Season', new_team_season_path %>


<br><br>
<hr>
<br><br>

app/views/team_seasons/new.html.erb
<h1>New Team Season</h1>

<%= render 'form', team_season: @team_season %>

<%= link_to 'Back', team_seasons_path %>

app/views/team_seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @team_season.index %>
</p>

<%= link_to 'Edit', edit_team_season_path(@team_season) %> |
<%= link_to 'Back', team_seasons_path %>